[tool.poetry]
name = "srvc-query-project"
version = "0.1.0"
description = ""
authors = ["John Shaffer <john@insilica.co>"]

[tool.poetry.dependencies]
python = "^3.10"
gpt-index = "^0.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
